# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    # Project coverage: Overall codebase coverage
    # Tracks improvements over time, aligns with pyproject.toml fail_under = 85
    project:
      default:
        target: auto      # Compare to base commit for trend tracking
        threshold: 2%     # Allow 2% variance (handles minor refactoring)
        base: auto        # Use parent commit as baseline

    # Patch coverage: Coverage of new code in PR
    # New code should be well-tested, but allow flexibility for platform-specific code
    patch:
      default:
        target: 90%       # New code should have high coverage
        threshold: 5%     # Allow 5% flexibility for edge cases (platform-specific branches, etc.)

# Pull request comment configuration
# Shows coverage changes to help reviewers understand impact
comment:
  layout: "diff, flags, files"  # Show diff, flag details, and file-by-file changes
  behavior: default             # Standard comment behavior
  require_changes: false        # Post comment even if coverage unchanged
  hide_project_coverage: false  # Show full project coverage stats

# Note: This config makes Codecov informational rather than strictly blocking.
# Our enforcement point is pyproject.toml's fail_under = 85 via pytest.
# Codecov provides visibility and tracks trends.
