name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  check-files:
    name: Check File Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for large files
        run: |
          # Find files larger than 1MB
          large_files=$(find . -type f -size +1M | grep -v "^./.git")
          if [ -n "$large_files" ]; then
            echo "Error: Large files detected (>1MB):"
            echo "$large_files"
            exit 1
          fi
